APPNAME="QBioBeat"
APPVERSION="0.1.4"
AUTHOR="ShadowKyogre"
DESCRIPTION="A small biorhythm application based on PyQt4."
YEAR="2013"
PAGE="http://shadowkyogre.github.com/QBioBeat/"
EMAIL="shadowkyogre.public@gmail.com"
